@echo  off
echo "start build libpng-1.6.45  Debug|x64"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\libpng-1.6.45\projects\vstudio\vstudio.sln"  /rebuild "DebugLibrary|x64" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build libpng-1.6.45  Unicode_Debug|x64 end"
echo " start build libpng-1.6.45  Release|x64"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\libpng-1.6.45\projects\vstudio\vstudio.sln"  /rebuild "ReleaseLibrary|x64" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build libpng  Release|x64 end"
echo "start build libpng-1.6.45  Debug|Win32"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\libpng-1.6.45\projects\vstudio\vstudio.sln"  /rebuild "DebugLibrary|Win32" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build libpng-1.6.45  Debug|Win32 end"
echo " start build libpng-1.6.45  Release|Win32"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\libpng-1.6.45\projects\vstudio\vstudio.sln"  /rebuild "ReleaseLibrary|Win32" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build libpng  Release|Win32 end"
echo "start build giflib-5.2.2  Debug|x64"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\giflib-5.2.2\build64\GifLib.sln"  /rebuild "Debug|x64" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build libpng-1.6.45  Unicode_Debug|x64 end"
echo " start build GifLib  Release|x64"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\giflib-5.2.2\build64\GifLib.sln"  /rebuild "Release|x64" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build GifLib  Release|x64 end"
echo "start build GifLib  Debug|Win32"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\giflib-5.2.2\build32\GifLib.sln"  /rebuild "Debug|Win32" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build GifLib  Debug|Win32 end"
echo " start build GifLib  Release|Win32"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\giflib-5.2.2\build32\GifLib.sln"  /rebuild "Release|Win32" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build GifLib  Release|Win32 end"
echo "start build cximage  Unicode_Debug|Win32"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\cximage\src\CxImageFull.sln"  /rebuild "Unicode_Debug|Win32" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build cximage  Unicode_Debug|Win32 end"
echo " start build cximage  Unicode_Release|Win32"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\cximage\src\CxImageFull.sln"  /rebuild "Unicode_Release|Win32" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build cximage  Unicode_Release|Win32 end"
echo "start build cximage  Unicode_Debug|x64"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\cximage\src\CxImageFull.sln"  /rebuild "Unicode_Debug|x64" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build cximage  Unicode_Debug|x64 end"
echo " start build cximage  Unicode_Release|x64"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\cximage\src\CxImageFull.sln"  /rebuild "Unicode_Release|x64" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build cximage  Unicode_Release|x64 end"
echo "start build Skia  Debug|x86"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\skia\skia.sln"  /rebuild "Debug|x86" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build skia  Debug|x86 end"
echo " start build skia  Release|x86"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\skia\skia.sln"  /rebuild "Release|x86" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build skia  Release|x86 end"
echo "start build Skia  Debug|x64"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\skia\skia.sln"  /rebuild "Debug|x64" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build skia  Debug|x64 end"
echo " start build skia  Release|x64"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\lib3rd\skia\skia.sln"  /rebuild "Release|x64" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build skia  Release|x64 end"
echo " start build RXSkin  Debug|x64"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\RXSkin.sln"  /rebuild "Debug|x64" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build RXSkin  Debug|x64 end"
echo " start build RXSkin  Release|x64"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\RXSkin.sln"  /rebuild "Release|x64" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build RXSkin  Release|x64 end"
echo " start build RXSkin  Debug|Win32"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\RXSkin.sln"  /rebuild "Debug|Win32" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build RXSkin  Debug|Win32 end"
echo " start build RXSkin  Release|Win32"
"E:\Program Files (x86)\Microsoft Visual Studio\\2019\Enterprise\Common7\IDE\devenv.exe" "F:\work\git\rxskin-DirectUI\tools\..\RXSkin.sln"  /rebuild "Release|Win32" /out "F:\work\git\rxskin-DirectUI\tools\output.txt"
echo "build RXSkin  Release|Win32 end"
echo "build successfully!"
pause
